#!/usr/bin/env bash
set -eo pipefail
. script/env
script/build-client
SERVER_IP=$(docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' ${PACKAGE_NAME}-server)
echo "Running client docker image..."
docker run --rm -it \
    -e "SERVER_IP=${SERVER_IP}" \
    -e "HTTP_PORT=8000" \
    -e "IPERF_PORT=5000" \
    ${DOCKER_OWNER}/${PACKAGE_NAME}-client $@
