#!/usr/bin/env bash
set -eo pipefail
. script/env
script/build-server
echo "Building server docker image..."
docker run --rm -it \
    --name ${PACKAGE_NAME}-server \
    -e "HTTP_PORT=8000" \
    -e "IPERF_PORT=7000" \
    -e "NETPERF_PORT=6000" \
    ${DOCKER_OWNER}/${PACKAGE_NAME}-server